version: '3'
services:
  ## Setting like Kubernetes with 1 pod(our localhost) but 2 containers, so it will use port 80 to open the application  
  app:
    build: ./
    network_mode: host
  proxy:
    build: ./nginx
    network_mode: host

  ## Setting if you want to use another port instead of 80
  # app:
  #   build: ./
  #   network_mode: service:proxy
  # proxy:
  #   build: ./nginx
  #   ports:
  #     - 3000:80
